name: Deploy Website

on:
  push:
    branches:
      - Live  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ftp://access1003390817.webspace-data.io
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ 

    - name: Send Discord Notification
      uses: rtCamp/action-discord-webhook@v2
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        message: "Deployment to Live server completed successfully!"
